### ISSUE TITLE
Texture2DArray compression doesn't change with platform switch in Unity 2020.2.0f1

### ISSUE THREAD

**Issue by carcasanchez** [pschraut/UnityTexture2DArrayImportPipeline#3]
Expected behaviour: When changing platforms, it's expected that Texture2DArrays switchs its compression format, as the original texture does. 
Formats are RGBA Compressed DTX5 for Windows, RGB(A) ASTC 6x6 for Android
Current behaviour: when switching platforms, original textures change formats, but the derived Texture2DArray maintains its old format.
Unity version is 2020.2.0f1. Texture2DArray Importer version is 1.2.0. Tested in an empty project.

Sept by step:
Create a Texture2DArray while Windows platform is selected and assign textures to it (from left to right, build settings, texture inspector and array inspector):
![imagen](https://user-images.githubusercontent.com/14940964/105968475-6c5fc800-6087-11eb-83f9-cbfbbfa17639.png)

Switch to Android platform, with Texture Compression set to ASTC in build settings. Texture format and array format mismatch after switch,
![imagen](https://user-images.githubusercontent.com/14940964/105968736-be085280-6087-11eb-9909-c10785fbd84b.png)

Same behaviour appears when order is reversed. Create a Texture2DArray in Android, and assign textures to it.
![imagen](https://user-images.githubusercontent.com/14940964/105969046-193a4500-6088-11eb-92e0-248741a9e73d.png)

Switch to Windows platform. Eexture format and array format mismatch again:
![imagen](https://user-images.githubusercontent.com/14940964/105969147-396a0400-6088-11eb-9c8d-1e101f1fd0c5.png)

**Comment by pschraut** [comment]
Thank you for the report. 

I was able to reproduce the same problem. It seems it's related to the Asset Pipeline version in Unity. In Unity 2019.4 you can switch between Asset Pipeline v1 and v2. The reported issue occurs with Asset Pipeline v2 only. I believe newer Unity versions don't offer the option to use v1 anymore.

I've submitted a bug-report to Unity Technologies describing the problem. I will update the issue here when I hear from them. Below you can find the bug-report case number from Unity and the video which was part of the bug-report.

(Case 1309841) AssetPipeline v2 does not reimport Texture2DArray when build target is changed
https://youtu.be/VBmFYf1Ih4g

**Comment by AtomicJoe1** [comment]
Great catch!

**Comment by pschraut** [comment]
Unity Technologies was able to reproduce the issue and it can be found in their public issue tracker now:
https://issuetracker.unity3d.com/issues/editor-does-not-reimport-texture2darray-when-build-target-is-changed

**Comment by AtomicJoe1** [comment]
Just voted for it :)

**Comment by pschraut** [comment]
I just released 1.3.0 , which should fix this issue. Can you give it a  try and let me know if it works for you too? Thanks go to Bastien of Unity Technologies for the help (basically providing the workaround/fix).
